version: "3.9"

services:

  db:
    image: postgres:16
    container_name: namma_bus_db
    restart: always
    environment:
      POSTGRES_DB: Namma_Bus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rahul@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: namma_bus_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./UI
    container_name: namma_bus_frontend
    volumes:
      - ./UI:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: