# Generated by Django 5.2.15 on 2026-07-02 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_type', models.CharField(choices=[('AC_SEATER', 'AC Seater'), ('NON_AC_SEATER', 'Non-AC Seater'), ('AC_SLEEPER', 'AC Sleeper'), ('NON_AC_SLEEPER', 'Non-AC Sleeper')], max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('amenities', models.CharField(blank=True, help_text='Comma separated e.g. WiFi,Charging Point,Blanket', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('SEATER', 'Seater'), ('SLEEPER', 'Sleeper')], default='SEATER', max_length=10)),
                ('deck', models.CharField(choices=[('LOWER', 'Lower'), ('UPPER', 'Upper')], default='LOWER', max_length=10)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('bus', 'seat_number')},
            },
        ),
    ]
